# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET localhost:8080/hello

# Expect to fail with 403

###

POST localhost:8080/join
Content-Type: application/json

{
  "username": "dima",
  "password": "123456"
}

###

POST localhost:8080/login
Content-Type: application/json

{
  "username": "dima",
  "password": "123456"
}

###

GET localhost:8080/hello
jwt: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImRpbWEifQ.qJz1spBuomwt5Odd8Iw_L1-6ZSVPWznI4_0o1aTAOUM

###

GET localhost:8080/messages
jwt: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6InVzZXIifQ.nZNV27ngJ2LWu2raQOrkCEcKFyLAmpdq1e7PewY1NfM

###

POST localhost:8080/messages
Content-Type: application/json
jwt: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6ImRpbWEifQ.qJz1spBuomwt5Odd8Iw_L1-6ZSVPWznI4_0o1aTAOUM

{
  "text": "Hello, I'm Dima!"
}

###
# { "id": "1", "username": "dima", "text": "hello, dima" } expected
